# Generated by Django 4.1.3 on 2023-02-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
